USE [master]
GO

/****** Object:  Database [GlassLewisCompanies]    Script Date: 4/14/2019 3:18:02 PM ******/
CREATE DATABASE [GlassLewisCompanies]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GlassLewisCompanies', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\GlassLewisCompanies.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GlassLewisCompanies_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\GlassLewisCompanies_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GlassLewisCompanies].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GlassLewisCompanies] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET ARITHABORT OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GlassLewisCompanies] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GlassLewisCompanies] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GlassLewisCompanies] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GlassLewisCompanies] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET RECOVERY FULL 
GO

ALTER DATABASE [GlassLewisCompanies] SET  MULTI_USER 
GO

ALTER DATABASE [GlassLewisCompanies] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GlassLewisCompanies] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GlassLewisCompanies] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GlassLewisCompanies] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GlassLewisCompanies] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GlassLewisCompanies] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GlassLewisCompanies] SET  READ_WRITE 
GO


